version: 2
jobs:
  build:
    docker:
      - image: liuchong/rustup:stable

    steps:
      # - setup_remote_docker:
      #     version: 17.10.0-ce

      - checkout

      - run:
          name: Environment setup
          command: |
            sudo apt-get install -y gcc-arm-none-eabi

            rustup install nightly
            rustup default nightly

            rustup component add rust-src

            cargo install xargo

      # - restore_cache:
      #     keys:
      #       - theapp-v1-{{ checksum "yarn.lock" }}-{{ checksum "elm-package.json" }}

      - run:
          command: |
            xargo build
            xargo build --examples

      # - store_artifacts:
      #     path: reports
      #     destination: reports

      # - store_test_results:
      #     path: reports/

      # - save_cache:
      #     key: theapp-v1-{{ checksum "yarn.lock" }}-{{ checksum "elm-package.json" }}
      #     paths:
      #       - node_modules
      #       - elm-stuff